# Generated by Django 3.0.6 on 2020-05-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(1, 'upcoming'), (2, 'incipient'), (3, 'completed'), (4, 'cancelled')], default=1, max_length=50, verbose_name='Appointment Status'),
        ),
    ]
