# Generated by Django 3.0.6 on 2020-05-07 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20200507_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rating',
            field=models.CharField(choices=[('UPCOMING', 'upcoming'), ('INCIPIENT', 'incipient'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default=datetime.datetime(2020, 5, 7, 16, 38, 29, 789409, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
